andymass/vim-matchup

- README.md
`else` should comes after `elseif`.
> Fix viml type in readme

- autoload/matchup/matchparen.vim
user can do something after offscreen match show and hide
> add MatchupOffscreenLeave and MatchupOffscreenEnter User autocmd

- doc/matchup.txt
> Copy explanations into help doc.

- .github/workflows/neovim.yml
- .github/workflows/vim.yml
Hello, maintainer.
Thanks for creating great Vim plugin.
I add `github-actions.` 
- This removes the gitlab dependency.
- Neovim stable and nightly tests are added.
- Since cache is effective, CI will be completed faster than before.
Could you check this PR?
If you don't need this pull request, feel free to close it.
> https://github.com/kazukazuinaina/vim-matchup/runs/774517904
> https://github.com/thinca/action-setup-vim
> [add] github actions

- .github/workflows/neovim.yml
- after/queries/python/matchup.scm
- autoload/matchup.vim
- autoload/matchup/delim.vim
- autoload/matchup/loader.vim
- autoload/matchup/misc.vim
- autoload/matchup/ts_engine.vim
- lua/treesitter-matchup.lua
- lua/treesitter-matchup/internal.lua
- lua/treesitter-matchup/lru.lua
- lua/treesitter-matchup/reload.lua
- lua/treesitter-matchup/util.lua
- test/vader/minvimrc
- test/vader/ts_py_motion.vader
Adds experimental support for python def/if/while/try.
> Add neovim tree-sitter integration

- after/queries/julia/matchup.scm
First time I've messed around with tree-sitter queries, so hopefully everything is done correctly. 
Everything seems to work fine in my basic testing.
> Adding julia support via tree-sitter

- after/queries/javascript/matchup.scm
- after/queries/jsx/matchup.scm
- after/queries/typescript/matchup.scm
This makes user to get more jump options (function/return and backticks).  Refactoring it this way also help us to get the right sense of hierarchy.
Earlier
Now
> Reuse schema from JavaScript for TypeScript

- lua/treesitter-matchup/internal.lua
> update nvim 0.7 treesitter api

- autoload/matchup/matchparen.vim
Basically this fix what is probably the underlying issue in #228 .
> Fix offscreen popup when there is a WinBar

- lua/treesitter-matchup/third-party/hl-info.lua
- lua/treesitter-matchup/third-party/utils.lua
https://github.com/neovim/neovim/pull/19931
> Fix for changes to nvim upstream TS/hl API, fix #241

- lua/treesitter-matchup/third-party/hl-info.lua
- lua/treesitter-matchup/third-party/utils.lua
Issue was caused by upstream changes to neovim or nvim-treesitter
> Merge TS playground changes from upstream (fixes #247)

- after/queries/javascript/matchup.scm
add try/catch/finally to javascript queries
> TS js: add try statement

- after/queries/bash/matchup.scm
This enhances queries for if loops with jumps for elif, break, and continue. This also adds support for while, for, and case statements.
> Additional bash TS queries

- after/queries/python/matchup.scm
Python's grammar has been updated - and soon nvim-ts will update too automatically so merge this whenever that happens sometime later today
> fix(treesitter): update python string query

- after/queries/c/matchup.scm
C will update & break sometime later today, but it now has a visible else_clause rule!
> fix(c): update queries from upstream

- after/queries/bash/matchup.scm
https://github.com/andymass/vim-matchup/assets/8136158/4380aec7-8721-40b2-81a1-1b8969e3c2d1
> Add TS query for heredoc redirection in Bash

- after/queries/svelte/matchup.scm
> feat(svelte)!: adapt queries to new parser

- after/queries/haskell/matchup.scm
See: 
- https://github.com/nvim-treesitter/nvim-treesitter/pull/6580
- https://github.com/tree-sitter/tree-sitter-haskell/pull/120
> Update haskell queries for tree-sitter-haskell v0.21.0 rewrite

- after/queries/templ/matchup.scm
- autoload/matchup/quirks.vim
Add sopport for templ (http://templ.guide)
Fixes #353
> feat: add support for templ

- after/queries/svelte/matchup.scm
> fix(svelte): adapt queries to new parser

- after/queries/perl/matchup.scm
I recently improved handling related to quotes, and i thought it was time to include
quote-matchups + other improvements. LMK if there's anything you'd like changed or added.
> feat(perl): add matchup for loops + quotes

- after/queries/zig/matchup.scm
This is most likely not everything. I'm not that familiar with the language. I missed this plugin when viewing zig files so I added what I could verify.
> Add zig queries

- after/queries/markdown/matchup.scm
- after/queries/markdown_inline/matchup.scm
show video
https://github.com/user-attachments/assets/4a850449-17c0-460f-a036-bb0e9dbfb77a
> add support markdown matchup
