andymass/vim-matchup

autoload/matchup/matchparen.vim

Implements a cool feature found in JetBrains IDE:s among others, where the line of the match is displayed in a popup, using the new [popup API](https://github.com/vim/vim/blob/db51730df1817fc4b6ecf5a065c69fac518ad821/runtime/doc/popup.txt) from Vim version 8.1. Currently it just replaces the status line feature, which is less than ideal. Could use some pointers on the best set of options to make it all configurable. Checks need to be added for availability of the popup feature. The implementation is also really rough, not to mention the popup API being unstable, but it works as a proof-of-concept.
The popup is displayed at the top of the window for matches above the view, and respectively at the bottom for matches below.
The fact that Vim does not have an autocommand for scrolling (issue …

Add popup for displaying off-screen matches

---

autoload/matchup/matchparen.vim
doc/matchup.txt

Using Neovim's floating window, or Vim 8.x popup.
Usage:
```viml
let g:matchup_matchparen_offscreen = {'method': 'popup'}
```
Screenshot:
I used bits from https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/hunk.vim#L388 and integrated appropriately.

Introduce new "popup" match display method

---

autoload/matchup/matchparen.vim

Thank you for the great plugin! I'm using your plugin with Vim 8.2 and its popup feature:
```vim
let g:matchup_matchparen_offscreen = {
\   'method': 'popup',
\ }
```
My environment:
- macOS 10.15.2
- Vim 8.2 (patch 1-319)
I prefer tab indent and sometimes popup window renders it as different width like this:
HTML file for reproducing the behavior (please try it with the option `:set tabstop=2`):
https://gist.github.com/cocopon/3de4fe7e43a5713ac473ae18688a10fd
I think Vim popup window maybe doesn't follow tabstop option of the current buffer. This pull request will fix the problem by replacing tab characters with spaces.
Neovim floating window works fine so I fixed only the code for Vim popup window.

Fix tab indent for popup

---

autoload/matchup/custom.vim

`matchup#delim#get_surrounding` now requires 3 arguments!

Update args for matchup#delim#get_surrounding in custom.vim

---

autoload/matchup/matchparen.vim

When `cursorline` is set, the left side is before the patched, right side is after the patched.
I think `CursorLineNr` highlight for `LineNr` in floating window preview is more identifiable than raw `LineNr`. If you don't like it, I can remove my personal preference.

offscreen highlight doesn't work when cursorline is set

---

autoload/matchup/matchparen.vim

I think `relativenumber` is used by those who want to be able to prepend a count to <kbd>j</kbd> and <kbd>k</kbd>, at least this is true for me. As a consequence, typing numbers and quickly hitting <kbd>j</kbd>/<kbd>k</kbd> (instead of <kbd>g</kbd><kbd>g</kbd>) has got so much in my muscle memory (and likely in that of some of those people too) that the non-relative number of the popup line disorients me. Note that hitting <kbd>%</kbd>/<kbd>g</kbd><kbd>%</kbd> instead of N+<kbd>j</kbd>/<kbd>k</kbd> is not always an option, for instance in a long chain of `if`/`elseif`/`elseif`/.../`else`/`endif`.
Therefore, why not showing the line number in the offscreen popup honoring the option that the user uses? The change addresses this. Let me know if you like it.
If you're afraid some `rnu` user …

Honor `relativenumber` in popup

---

.gitignore

Add `doc/tags` to `.gitignore` to suppress the "untracked content" message after running `:helptags` when this repository is a submodule.

Ignore help tags

---

lua/treesitter-matchup/internal.lua
test/vader/ts_py_motion.vader

Previously, in the example below, placing the cursor on line 1 would highlight every elif and else in the whole block of code. % would jump to line 4, then % from there would cycle between lines 2, 4 and 6.
```
1   if noice:
2       if yeah:
3           pass
4       elif no:
5           pass
6       else:
7           pass
8   elif blah:
9       pass
10   else:
11       pass
```
With the change, which I think the code had contemplated given there was already an unused `M.containing_scope(node, bufnr, info.key)` call, % will only move between ifs and elses that are in the same `@scope.if_`, and not to any inner scopes. Hence the example will have two mutually exclusive %-cycles: [1, 8, 10] and [2, 4, 6].

tree-sitter: ignore matches in inner scopes

---

after/queries/ruby/matchup.scm

Ability to matchup `unless` for Ruby language.

Add "unless" matchup for Ruby

---

README.md
autoload/matchup/motion.vim
doc/matchup.txt

This PR also fixes some ambiguities (related to `g:matchup_motion_override_Npercent`) and a typo in the documentation.

Always override N% if `g:matchup_motion_override_Npercent` >= 100

---

autoload/matchup/matchparen.vim

This tiny PR adds support for the window border options added in Neovim 0.5, as described in `:help nvim_open_win()`, to the offscreen popup. I don't usually code in Vimscript, so let me know if there's anything you'd like me to change. Thanks!

Support offscreen popup borders options for Neovim 0.5+

---

autoload/matchup/matchparen.vim

Following https://github.com/neovim/neovim/pull/15832
It is no longer necessary to subtract border height from row.

fix: correct floating window position in Neovim 0.6 nightly

---

autoload/matchup.vim
autoload/matchup/matchparen.vim
autoload/matchup/where.vim

I have issues with specific char that is used as a marker by default, so it would be nice to add the ability to change it.
Here is how it looks for me:
And after adding this options, it looks like this:
let g:matchup_matchparen_start_sign = ''
let g:matchup_matchparen_end_sign = ''

Add option to change virt text markers

---

lua/treesitter-matchup/internal.lua

The `goto` keyword is introduced in a newer version of lua, running this
plugin with an older version of lua will produce an error:
```
Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader#init_buffer[5]..matchup#ts_engine#is_enabled[4]..<SNR>126_forward:
line    1:
E5108: Error executing lua vim.lua:63: ...local/share/nvim/plugins/vim-matchup/lua/treesitter-matchup/internal.lua:195: '=' expected near 'continue'
stack traceback:
[C]: in function 'error'
vim.lua:63: in function <vim.lua:57>
[C]: in function 'require'
[string "luaeval()"]:1: in main chunk
Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader#init_buffer[15]..matchup#ts_engine#is_hl_enabled[4]..<SNR>126_forward:
line    1:
E5108: Error executing lua …
```

Avoid goto logic in internal.lua

---

lua/treesitter-matchup/internal.lua

I misunderstood the new default API in `nvim`  when I wrote #216 . This fixes that.
This comment clarified what `vim.treesitter.query.get_node_text` was actually returning: https://github.com/nvim-treesitter/nvim-treesitter/pull/2801#issuecomment-1101555994

Fix _node_text

---

after/queries/ruby/matchup.scm

HI @andymass I'm really enjoying the treesitter support of vim-matchup. It gave me the confidence to add a feature I've always wanted, moving between the pipes delimiting block param arguments ie. `[].map { |arg_one, arg_two| }`.

TS Ruby add block param delimiters

---

after/queries/rust/matchup.scm

Support for:
```rust
if let Ok(pat) = result {
} else {}
```

TS Rust add if let.

---

after/queries/javascript/matchup.scm

Resolves: https://github.com/andymass/vim-matchup/issues/248
---
```js
function do_it() {
const array = [1, 2, 3, 4];
if (array.lenth > 5) {
return 0;
}
const yyy = function () {
return 1;
};
yy = function () {
return 1;
};
const xxx = () => {
return "xx";
};
xx = () => {
return "xx";
};
for (const x of xs) {
return 0;
}
array.forEach((x) => {
if (x % 2 == 0) {
xx();
return;
}
console.log(x);
});
return 0;
}
```

Fix javascript treesitter queries for function

---

lua/treesitter-matchup/internal.lua

This PR fixes calls to [is_enabled](https://github.com/nvim-treesitter/nvim-treesitter/blob/8ec59aee8097c64fcf27d1dbd77ea181c50846c5/lua/nvim-treesitter/configs.lua#L346) whcih requires `bufnr`. Currently user's custom [disable function](https://github.com/nvim-treesitter/nvim-treesitter/blob/8ec59aee8097c64fcf27d1dbd77ea181c50846c5/lua/nvim-treesitter/configs.lua#L364) doesn't receive proper arguments.

Pass bufnr to TS configs.is_enabled

---

after/queries/rust/matchup.scm

After https://github.com/tree-sitter/tree-sitter-rust/commit/6ebdb1dc6cf4c19d8bae1d04f7bad44408e877d8 the node types `if_let_expression` and `while_let_expression` no longer exist but are merged into the normal `if_expression` and `while_expression`. This PR edits the Rust queries accordingly.
---
Side note: The `if_expression`s are only matched when their parent is either a `block`, `expression_statement` or `let_declaration`. Optimally we could just match `if_expression` with any parent except for `else_clause`.

Fix `if let` expressions in Rust

---

README.md

Hi! @andymass - This PR is just to recommend the correct parameter (`setup`) according to the `packer.nvim` documentation (see https://github.com/wbthomason/packer.nvim#specifying-plugins) and based on my experience for load options. For plugins built with VimScript, it is recommended to load options before the plugin loads, so that the plugin can detect them correctly, unlike plugins built entirely in Lua, which must be loaded before customization. Would you be so kind as to accept it ?? :)

fix(readme): `setup` is used to load options with `packer.nvim`

---

README.md
doc/matchup.txt

Hi,
cool plugin! I had installed that for years, but only today I actually took the time to read through the whole documentation.
I stumbled upon two things that made me scratch my head for a minute, until I concluded they are just typos in the documentation. The diff should be self-explanatory.

fix typos in readme and doc about exclusive motion in visual mode

---

lua/treesitter-matchup/internal.lua
lua/treesitter-matchup/third-party/hl-info.lua
lua/treesitter-matchup/third-party/utils.lua

As in #215, `nvim-treesitter` has deprecated `is_in_node_range` (nvim-treesitter/nvim-treesitter@2c2430d) in favor of `vim.treesitter.is_in_node_range`. This PR makes that change.

Update nvim 0.7 treesitter api (again)

---

after/queries/ruby/matchup.scm

Now it'll match `singleton_class` like:
```ruby
class << self
end
```

Add ruby singleton class match

---

lua/treesitter-matchup/compat.lua
lua/treesitter-matchup/internal.lua
lua/treesitter-matchup/third-party/query.lua

ref: neovim/neovim@cbbf8bd
~~The new function calls are not yet on neovim stable, and have just been updated. I suggest to merge this after the release of `0.9.0`.~~
We could make a compatibility module [similar to nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/compat.lua) (the devs told me they shouldn't be used by 3rd party plugins, so we should make our own?).

fix: Move to non-deprecated `vim.treesitter` function calls

---

after/ftplugin/javascriptreact_matchup.vim

Noticed enabling the `tagnameonly` preference worked for my `.tsx` files, but not for my `.jsx` ones. This change should fix it.

Enable tagnameonly functionality for jsx files

---

after/queries/glimmer/matchup.scm

Add support for:
* tags including self closing
* blocks (including `{{else}}`)
* mustache statements (e.g. `{{foo}}`)
* sub expressions (e.g. `(eq foo bar)`)

Add glimmer support in treesitter

---

after/queries/nix/matchup.scm

Implemented nix support:
* Added `let`/`in` matching:
* Added jumping to end for `binding`s that hold a `function_expression`

Added nix support

---

after/queries/c/matchup.scm

Let me know if this is not the right way (e.g. function should be based on a "function" keyword like def/func/fun/fn)

feat(c): add function and loop queries

---

after/queries/haskell/matchup.scm

- Delete fun and sig queries, as these can be a bit annoying.
- More stable `mid.<x>.<n>` captures. The previous ones don't always match, as they can be arbitrarily nested.

Some haskell tree-sitter query improvements

---

after/queries/ecma/matchup.scm

Behavior before change:
Behavior after change:

Fix ECMA method function return

---

after/ftplugin/tex_matchup.vim

Added matchup support for a bunch of LaTeX3 macros. (They are documented in `source3.pdf` and are the stable ones. In `l3candidates` I didn’t find any experimental macros which need matchup support anyway.)
And here’s a test file which may be helpful: [`test-expl3-matchup.txt`](https://github.com/andymass/vim-matchup/files/12379580/test-expl3-matchup.txt) (maybe `:setf tex` is needed). And there’s something wrong with it: `\if_true|false:` has no signature `w`. (just aware of that
N.B., the only changed line is:
```vim
" let l:match_words .= ',\\if\%(\w\|@\)*\>:\\else\>:\\fi\>'
let l:match_words .= ',\\if\%(\:w\|\%(\w\|@\)*\)\>:\\else\:\?\>:\\fi\:\?\>'
```
since the LaTeX3 version (`\if:w\else:\fi:`) overlaps with the TeX version, and therefore the `\:` is placed before the `\>`. Thus a …

feat: add LaTeX3 matchup support.

---

after/queries/rust/matchup.scm

Also remove `@open.function` from closure return. As far as I can tell, is currently broken. I couldn't figure out a way to have both closure open / return and || pairs.
If there's a better way to handle this, or if I'm missing something, happy to learn.
If closure return is more important than || pairs, also happy to close this pull request.

Add Rust closure || pairs

---

after/queries/go/matchup.scm

https://go.dev/tour/methods/4
```
func (v *Vertex) Scale(f float64) {
v.X = v.X * f
v.Y = v.Y * f
}
```

fix: go methods query missing

---

after/queries/ecma/matchup.scm

pending https://github.com/nvim-treesitter/nvim-treesitter/pull/6024

fix(ecma): `function` -> `function_expression`

---

after/queries/fish/matchup.scm

One thing that I'm not sure about is the `else if` handling: This is parsed as `(else_if_clause "else" "if" ...)` with two separate keywords. The query correctly matches this, but matchup will only highlight the `else`, whereas it would be great if it could highlight the entire `"else" "if"` including the whitespace between. Can this be done?

Add fish queries

---

lua/treesitter-matchup/third-party/query.lua

After https://github.com/neovim/neovim/commit/6913c5e1d975a11262d08b3339d50b579e6b6bb8 it is necessary to opt-in explicitly to the old behavior.
Fixes #360.

fix(query): use explicitly the legacy behavior

---

after/ftplugin/tex_matchup.vim

texMathZoneX was renamed to texMathZoneTI in
[vimtex 0cf45fd3f8128f427588098389634233738682f4](https://github.com/lervag/vimtex/commit/0cf45fd3f8128f427588098389634233738682f4)
Related: https://github.com/andymass/vim-matchup/issues/123
cc: @lervag

use texMathZoneTI for vimtex v2.11

---

autoload/matchup/matchparen.vim

Behaviour is in line with the current docs, i.e.: https://github.com/andymass/vim-matchup/blob/aca23ce53ebfe34e02c4fe07e29e9133a2026481/doc/matchup.txt#L698-L701

Accept offscreen popup borders as lists

---

after/queries/haskell/matchup.scm

Something appears to have changed, either in Neovim or in tree-sitter-haskell.
When opening a Haskell file, I'm greeted with a recurring error `impossible pattern: constructor/record`.
This seems to fix it.

fix(queries/haskell): constructor/record -> record

---

autoload/matchup/matchparen.vim

I found a pretty obnoxious bug that can occur when a winbar is setup with the matchup floating windows where it can trigger `E36: Not enough room` error.
I've attached a video of the error occuring, and while I did try to solve it on the lualine side by conditionally disabling winbar in floating windows, I couldn't ever seem to get it to work. The only fix I found was just to wholesale disable winbar in these floating windows:
https://github.com/user-attachments/assets/2241d86d-3e55-42eb-8ca5-b65505b32fef
Unclear if this is the preferred way to do it, but I imagine a winbar shouldn't ever be shown in these scenarios regardless, so felt safe? Happy to change it to check for an option though if you'd prefer.

Disable winbar on neovim 0.8.0 and later

---

lua/treesitter-matchup/internal.lua

I believe this was the intention of the original change in (#217): there is some mixing of terminology in the review discussion, but I believe the intention was to extract the first line in the match, as suggested in the linked discussion, and not the string up to the first whitespace.

Split treesitter matches at newlines instead of whitespace

---

autoload/matchup/matchparen.vim

Fixes #391
Floating windows are not cleared. The reason is that `win_id2win()` returns 0 for some reason after some new changes in neovim.
Note that `nvim_open_win` returns a `window-ID`, and `nvim_win_close` needs a `window-ID` too. So in general, I don't know if `win_id2win` is necessary at all.

fix(popup): clear popup window on nightly nvim >= 0.12

---

autoload/matchup/matchparen.vim

Fixes #394 
This PR makes the line silently fail. I tried deferring it's execution, but it wasn't allowed either when in sandbox/modeline.
Another option would be to `throw` a new error, mentioning where the error is coming from (setting the value of `signcolumn` on a modeline). I guess a third option could be to rework the logic of the plugin to check if `signcolumn` is set each time it needs to, instead of relying on an autocmd of when it value changes. But, I don't know this side of the codebase (nor vimscript) enought to make such change.

fix: silently fail nvim_buf_clear_namespace call in sandbox/modeline

---

autoload/matchup.vim

Should fix the issue described in https://github.com/andymass/vim-matchup/pull/390#issuecomment-3047043335

fix: enable treesitter virtual text by default

---

after/queries/haskell/matchup.scm

Fixes https://github.com/andymass/vim-matchup/commit/e4aae30b3f3401492c8cab262b2760ff230aa69e#commitcomment-161698373

fix(haskell): use the correct captures for lambda case

---

after/queries/go/matchup.scm

Current queries seem broken/outdated.
```
Error in function matchup#motion#find_matching_pair[31]..matchup#delim#get_current[1]..<SNR>51_get_delim_multi[3]..matchup#ts_engine#get_delim[3]..<SNR>45_forward:
line    1:
E5108: Lua: /home/phan/b/neovim/runtime/lua/vim/treesitter/query.lua:374: Query error at 21:3. Impossible pattern:
(if_statement
^
stack traceback:
[C]: in function '_ts_parse_query'
/home/phan/b/neovim/runtime/lua/vim/treesitter/query.lua:374: in function 'fn'
/home/phan/b/neovim/runtime/lua/vim/func/_memoize.lua:78: in function 'fn'
/home/phan/b/neovim/runtime/lua/vim/func/_memoize.lua:78: in function 'get'
...han/lazy/vim-matchup/lua/treesitter-matchup/internal.lua:82: in function 'fn'
...-matchup/lua/treesitter-matchup/third-party/ts-utils.lua:19: in function …
```

fix(go): update broken queries
